formsapp/urls.py
from django.urls import path
from formsapp import views

# class based built in View
from django.views.generic import TemplateView

urlpatterns = [
    path('contact-us/', views.ContactUsFormView.as_view()),
    path('register/', views.register),
    path('create-book/', views.BookFormView.as_view()),
    path('about-us/', TemplateView.as_view(template_name='formsapp/aboutus.html')),
    path('contactus-success/', TemplateView.as_view(template_name='formsapp/contactus-success.html')),
    path('books/', views.BookListView.as_view()),
    path('create-author/', views.AuthorCreateView.as_view()),
    path('update-author/<int:pk>', views.AuthorUpdateView.as_view()),
    path('author-success/<int:author_id>', views.author_create_success, name='author-detail'),
    path('author-delete/<int:pk>', views.AuthorDeleteView.as_view())
]

secondapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('formsapp/', include('formsapp.urls'))
]

formsapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=30)
    pages = models.IntegerField()
    price = models.FloatField(null=True, blank=True)
    publisheddate = models.DateField(null=True, blank=True)

class Author(models.Model):
    name = models.CharField(max_length=30)
    ratings = models.IntegerField()

    def get_absolute_url(self):
        return reverse('author-detail', kwargs={'author_id': self.pk})

    def __str__(self):
        return self.name

formsapp/forms.py
from django import forms
from formsapp.models import Book

class ContactForm(forms.Form):
    email = forms.EmailField(label='Email Address', required=True,\
        error_messages={'required':'Would need ur email','invalid': 'Hey, enter right format email'})
    mobile = forms.CharField(label='Mobile Number', required=False, max_length=10, min_length=8)
    message = forms.CharField(required=True, widget=forms.Textarea, max_length=100,\
        error_messages={'required': 'We need to hear from u!'})

    # custom validation
    def clean_message(self):
        message = self.cleaned_data['message']
        words = message.split(' ')
        if len(words) < 10:
            raise forms.ValidationError('Please be elaborate!')
        return message

class RegisterForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput)
    country = forms.ChoiceField(required=True, choices=[('IN','India'),('USA','United states')])
    gender = forms.ChoiceField(required=True, widget=forms.RadioSelect, \
        choices=(('M', 'Male'),('F', 'Female')))
    '''preferences = forms.ChoiceField(widget=forms.CheckboxSelectMultiple,\
        choices=(('Sports','Sports'),('Travel','Travel')))'''
    profilepic = forms.FileField(required=False)


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title','price','pages', 'publisheddate']
        widgets = {
            'publisheddate': forms.DateInput(attrs={'class':'datepicker'})
        }

formsapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from formsapp.forms import ContactForm, RegisterForm, BookForm
from django.views import View
from django.views.generic import FormView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from formsapp.models import Book, Author
from datetime import datetime

# Create your views here.

# view functions
# view classes

class ContactUsFormView(FormView):
    template_name = 'formsapp/contactus.html'
    form_class = ContactForm
    success_url = '/formsapp/contactus-success'

    def form_valid(self, form):
        contactdata = form.cleaned_data
        print('Sending email to...')
        print(contactdata)

        return super().form_valid(form)

'''class ContactUsView(View):
    def get(self, request):
        contactform = ContactForm()
        return render(request, 'formsapp/contactus.html', {
            'form': contactform
        })

    def post(self, request):
        contactform = ContactForm(request.POST)
        if contactform.is_valid():
            cdata = contactform.cleaned_data
            print(cdata)
            return HttpResponse('We will get back to u!')
        else:
            return render(request, 'formsapp/contactus.html', {
                'form': contactform
            })
'''

'''def contactus(request):
    if request.method == 'POST':
        contactform = ContactForm(request.POST)
        if contactform.is_valid():
            cdata = contactform.cleaned_data
            print(cdata)
            return HttpResponse('We will get back to u!')
    else:
        contactform = ContactForm()

    return render(request, 'formsapp/contactus.html', {
        'form': contactform
    })
'''

def register(request):
    if request.method == 'POST':
        registerform = RegisterForm(request.POST, request.FILES)
        if registerform.is_valid():
            rdata = registerform.cleaned_data
            print(rdata)
            handle_uploaded_file(request.FILES['profilepic'])
            return HttpResponse('Success in register')
    else:
        registerform = RegisterForm()

    return render(request, 'formsapp/register.html', {
        'form': registerform
    })

def handle_uploaded_file(file_to_upload):
    # print(file_to_upload.name)
    # print(file_to_upload.content_type)
    with open('/tmp/profile_pics/{0}'.format(file_to_upload.name), mode='wb') as fp:
        for chunk in file_to_upload.chunks():
            fp.write(chunk)

class BookFormView(FormView):
    template_name = 'formsapp/create-book.html'
    form_class = BookForm

    def form_valid(self, modelform):
        book = modelform.save()
        if book.id:
            return HttpResponse('Success')
        return HttpResponse('Failure')

class BookListView(ListView):
    # model = Book # Book.objects.all()
    # by default
    # formsapp/book_list_view.html
    # object_list
    queryset = Book.objects.filter(price__gt=800)
    context_object_name = 'book_list'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['datetime'] = datetime.now()

        return context_data

class AuthorCreateView(CreateView):
    model = Author
    fields = '__all__'

class AuthorUpdateView(UpdateView):
    model = Author
    fields = '__all__'

class AuthorDeleteView(DeleteView):
    model = Author
    success_url = '/formsapp/contact-us/'   

def author_create_success(request, author_id):
    return HttpResponse('success' + str(author_id))

'''def createbook(request):
    if request.method == 'POST':
        bookform = BookForm(request.POST)
        if bookform.is_valid():
            book = bookform.save()
            if book.id:
                return HttpResponse('Success')
            else:
                return HttpResponse('Failure')
    else:
        bookform = BookForm()
    return render(request, 'formsapp/create-book.html', {
        'form': bookform
    })
'''

formsapp/templates/formsapp/aboutus.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>About us</title>
  </head>
  <body>
    About Us and our organization!!
    <hr>
  </body>
</html>

formsapp/templates/formsapp/author_confirm_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Delete Confirm?</title>
  </head>
  <body>
      <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }}?</p>
        <input type="submit" value="Delete">
      </form>
  </body>
</html>

formsapp/templates/formsapp/author_form.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Create Author</title>
  </head>
  <body>
    <form method="post" novalidate>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Create">
    </form>
  </body>
</html>

formsapp/templates/formsapp/book_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Book List</title>
  </head>
  <body>
    {{ datetime }}
    <table border="1">
      <thead>
        <tr>
          <td>Title</td>
          <td>Price</td>
          <td>Pages</td>
        </tr>
      </thead>
      <tbody>
        {% for book in book_list %}
          <tr>
            <td>{{ book.title }}</td>
            <td>{{ book.price }}</td>
            <td>{{ book.pages }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>

formsapp/templates/formsapp/contactus-success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Succes</title>
  </head>
  <body>
    We will get back to u!
  </body>
</html>

formsapp/templates/formsapp/contactus.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Contact us</title>
    <link rel="stylesheet" href="{% static 'formsapp/css/styles.css' %}">
  </head>
  <body>
    <form method="post" novalidate>
      {% csrf_token %}
      <p>
        <label for="id_mobile">Mobile</label>
        {{ form.mobile }}
        {{ form.mobile.errors }}
      </p>
      <p>
        <label for="id_email">Email</label>
        {{ form.email }}
        {{ form.email.errors }}
      </p>
      <p>
        <label for="id_message">Message</label>
        {{ form.message.errors }}
        {{ form.message }}
      </p>
      <input type="submit" value="Submit">
    </form>
  </body>
</html>

formsapp/templates/formsapp/create-book.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Create Book</title>
    <script src="{% static 'formsapp/js/jquery.js' %}"></script>
    <script src="{% static 'formsapp/js/jquery-ui.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'formsapp/js/jquery-ui.min.css' %}">
  </head>
  <body>
    <form method="post" novalidate>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Create">
    </form>
    <script>
    $( function() {
      $( ".datepicker" ).datepicker();
    });
</script>
  </body>
</html>

formsapp/templates/formsapp/register.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Register Here!</title>
  </head>
  <body>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Register">
    </form>
  </body>
</html>